POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
    "user_id": "1",
    "user_message": "Olá, qual é o seu nome?"
}

###

POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
    "chat_id": "1f7ff502-064c-4f5b-ba5c-d5399f9f5e15",
    "user_id": "1",
    "user_message": "Eu quero saber mais sobre arquitetura de software"
}